const REQUEST_IDENTIFIERS = 'REQUEST_IDENTIFIERS'
const RECEIVE_IDENTIFIERS = 'RECEIVE_IDENTIFIERS'

const CREATE_IDENTIFIERS = 'CREATE_IDENTIFIERS'

const UPDATE_IDENTIFIERS = 'UPDATE_IDENTIFIERS'
const DELETE_IDENTIFIERS = 'DELETE_IDENTIFIERS'

export {
  REQUEST_IDENTIFIERS,
  RECEIVE_IDENTIFIERS,
  CREATE_IDENTIFIERS,
  UPDATE_IDENTIFIERS,
  DELETE_IDENTIFIERS
}
